// Home23 — PM2 Process Configuration (auto-generated)
// Do not edit manually — regenerated by: node cli/home23.js agent create
//
// Agents: jerry

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const HOME23 = __dirname;
const ENGINE = path.join(HOME23, 'engine');

function loadYaml(filePath) {
  if (!fs.existsSync(filePath)) return {};
  return yaml.load(fs.readFileSync(filePath, 'utf8')) || {};
}

const homeConfig = loadYaml(path.join(HOME23, 'config', 'home.yaml'));
const secrets = loadYaml(path.join(HOME23, 'config', 'secrets.yaml'));
const ollamaLocalUrl = homeConfig.providers?.['ollama-local']?.baseUrl || 'http://127.0.0.1:11434';

const commonEnv = {
  NODE_ENV: 'production',
  COSMO_CONFIG_PATH: path.join(HOME23, 'configs', 'base-engine.yaml'),
  EMBEDDING_BASE_URL: `${ollamaLocalUrl}/v1`,
  LOCAL_LLM_BASE_URL: `${ollamaLocalUrl}/v1`,
  OLLAMA_CLOUD_API_KEY: secrets.providers?.['ollama-cloud']?.apiKey || '',
  ANTHROPIC_AUTH_TOKEN: secrets.providers?.anthropic?.apiKey || '',
  OPENAI_API_KEY: secrets.providers?.openai?.apiKey || '',
  XAI_API_KEY: secrets.providers?.xai?.apiKey || '',
};

// Generate evobrew config from home.yaml on every PM2 load (start/restart/reload)
(function generateEvobrewConfig() {
  try {
    const instancesDir = path.join(HOME23, 'instances');
    const agents = [];
    if (fs.existsSync(instancesDir)) {
      for (const name of fs.readdirSync(instancesDir).sort()) {
        const cfgPath = path.join(instancesDir, name, 'config.yaml');
        if (!fs.existsSync(cfgPath)) continue;
        const ac = loadYaml(cfgPath);
        agents.push({
          id: name,
          name: ac.agent?.displayName || name,
          url: `http://localhost:${ac.ports?.bridge || (5004 + agents.length * 10)}`,
          endpoint: '/api/chat',
          api_key: '',
          enabled: true,
          capabilities: { maxOutputTokens: 64000, contextWindow: 128000 },
        });
      }
    }

    // Research brains from cosmo23
    const cosmo23RunsDir = path.join(HOME23, 'cosmo23', 'runs');
    const researchBrains = {};
    if (fs.existsSync(cosmo23RunsDir)) {
      for (const name of fs.readdirSync(cosmo23RunsDir).sort()) {
        if (fs.existsSync(path.join(cosmo23RunsDir, name, 'state.json.gz'))) {
          researchBrains[name] = path.join(cosmo23RunsDir, name);
        }
      }
    }

    // Allowed models from home.yaml
    const providers = homeConfig.providers || {};
    const allowedModels = {};
    for (const [pid, pc] of Object.entries(providers)) {
      if (pc?.defaultModels?.length) allowedModels[pid] = pc.defaultModels;
    }

    const evoConfig = {
      _generated: true, _generatedAt: new Date().toISOString(), _home23: true,
      _source: 'Generated by ecosystem.config.cjs — do not edit',
      providers: {
        anthropic: { oauth: false },
        openai: {},
        xai: {},
        ollama: { url: providers['ollama-local']?.baseUrl || 'http://127.0.0.1:11434' },
        'ollama-cloud': { url: providers['ollama-cloud']?.baseUrl || 'https://ollama.com/v1' },
        local_agents: agents,
      },
      allowedModels,
      defaults: { provider: homeConfig.chat?.defaultProvider || '', model: homeConfig.chat?.defaultModel || '' },
      brain: {
        defaultPath: agents.length > 0 ? path.join(instancesDir, agents[0].id, 'brain') : '',
        agentBrains: Object.fromEntries(agents.map(a => [a.id, path.join(instancesDir, a.id, 'brain')])),
        researchBrains,
      },
      features: { brains: {
        enabled: true,
        directories: [
          ...agents.map(a => path.join(instancesDir, a.id)),
          ...(fs.existsSync(cosmo23RunsDir) ? [cosmo23RunsDir] : []),
        ],
      }},
      server: { port: homeConfig.evobrew?.port || 3405, host: '0.0.0.0' },
      security: { profile: 'local' },
      terminal: { enabled: true, maxSessions: 5 },
    };

    fs.writeFileSync(path.join(HOME23, 'evobrew', 'config.json'), JSON.stringify(evoConfig, null, 2));
  } catch (e) {
    console.warn('[ecosystem] evobrew config generation failed (non-fatal):', e.message);
  }
})();

module.exports = {
  apps: [

    // ── jerry ──
    {
      name: 'home23-jerry',
      script: 'src/index.js',
      cwd: ENGINE,
      node_args: '--expose-gc --max-old-space-size=768',
      max_memory_restart: '900M',
      autorestart: true, watch: false, merge_logs: true,
      out_file: path.join(HOME23, 'instances', 'jerry', 'logs') + '/engine-out.log',
      error_file: path.join(HOME23, 'instances', 'jerry', 'logs') + '/engine-err.log',
      env: { ...commonEnv, COSMO_RUNTIME_DIR: path.join(HOME23, 'instances', 'jerry', 'brain'), COSMO_WORKSPACE_PATH: path.join(HOME23, 'instances', 'jerry', 'workspace'), DASHBOARD_PORT: '5002', COSMO_DASHBOARD_PORT: '5002', REALTIME_PORT: '5001', MCP_HTTP_PORT: '5003', INSTANCE_ID: 'home23-jerry' },
    },
    {
      name: 'home23-jerry-dash',
      script: 'src/dashboard/server.js',
      cwd: ENGINE,
      autorestart: true, watch: false, merge_logs: true,
      out_file: path.join(HOME23, 'instances', 'jerry', 'logs') + '/dashboard-out.log',
      error_file: path.join(HOME23, 'instances', 'jerry', 'logs') + '/dashboard-err.log',
      env: { ...commonEnv, COSMO_RUNTIME_DIR: path.join(HOME23, 'instances', 'jerry', 'brain'), COSMO_WORKSPACE_PATH: path.join(HOME23, 'instances', 'jerry', 'workspace'), DASHBOARD_PORT: '5002', COSMO_DASHBOARD_PORT: '5002', REALTIME_PORT: '5001', MCP_HTTP_PORT: '5003', INSTANCE_ID: 'home23-jerry' },
    },
    // NOTE: standalone feeder (feeder/server.js) removed — the engine's built-in
    // DocumentFeeder handles ingestion with LLM compilation. See engine/src/ingestion/.
    {
      name: 'home23-jerry-harness',
      script: 'dist/home.js',
      cwd: HOME23,
      autorestart: true, watch: false, merge_logs: true,
      out_file: path.join(HOME23, 'instances', 'jerry', 'logs') + '/harness-out.log',
      error_file: path.join(HOME23, 'instances', 'jerry', 'logs') + '/harness-err.log',
      env: { HOME23_AGENT: 'jerry', OLLAMA_CLOUD_API_KEY: commonEnv.OLLAMA_CLOUD_API_KEY, ANTHROPIC_AUTH_TOKEN: commonEnv.ANTHROPIC_AUTH_TOKEN, OPENAI_API_KEY: commonEnv.OPENAI_API_KEY, XAI_API_KEY: commonEnv.XAI_API_KEY },
    },

    // ── evobrew (shared) ──
    {
      name: 'home23-evobrew',
      script: 'server/server.js',
      cwd: path.join(HOME23, 'evobrew'),
      autorestart: true, watch: false, merge_logs: true,
      out_file: path.join(HOME23, 'logs', 'evobrew-out.log'),
      error_file: path.join(HOME23, 'logs', 'evobrew-err.log'),
      env: {
        ...commonEnv,
        ANTHROPIC_API_KEY: secrets.providers?.anthropic?.apiKey || commonEnv.ANTHROPIC_AUTH_TOKEN || '',
        COSMO_ADMIN_MODE: 'true',
        PORT: String(homeConfig.evobrew?.port || 3405),
        EVOBREW_CONFIG_DIR: path.join(HOME23, 'evobrew'),
        NODE_ENV: 'production',
      },
    },

    // ── cosmo23 (shared) ──
    {
      name: 'home23-cosmo23',
      script: 'server/index.js',
      cwd: path.join(HOME23, 'cosmo23'),
      autorestart: true, watch: false, merge_logs: true,
      out_file: path.join(HOME23, 'logs', 'cosmo23-out.log'),
      error_file: path.join(HOME23, 'logs', 'cosmo23-err.log'),
      env: {
        ...commonEnv,
        COSMO23_PORT: String(homeConfig.cosmo23?.ports?.app || 43210),
        COSMO23_WS_PORT: String(homeConfig.cosmo23?.ports?.websocket || 43240),
        COSMO23_DASHBOARD_PORT: String(homeConfig.cosmo23?.ports?.dashboard || 43244),
        COSMO23_MCP_HTTP_PORT: String(homeConfig.cosmo23?.ports?.mcp || 43247),
        COSMO23_CONFIG_DIR: path.join(HOME23, 'cosmo23', '.cosmo23-config'),
        COSMO_RUNTIME_DIR: path.join(HOME23, 'cosmo23', 'runs'),
        COSMO_REFERENCE_RUNS_PATHS: homeConfig.cosmo23?.source ? homeConfig.cosmo23.source + '/runs' : '',
        NODE_ENV: 'production',
      },
    },
  ],
};
